version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
